# Imports

In [1]:
import pandas as pd
import numpy as np
import os
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load the Data

In [2]:
df = pd.read_csv("C:/Users/keshi/Downloads/archive (1)/Output_file1/EDA.csv")

In [3]:
df.head()

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N,Cluster
0,1,D,Flight,4,2,177,3,low,F,44,1233,1,0
1,2,F,Flight,4,5,216,2,low,M,59,3088,1,0
2,3,A,Flight,2,2,183,4,low,M,48,3374,1,0
3,4,B,Flight,3,3,176,4,medium,M,10,1177,1,0
4,5,C,Flight,2,2,184,3,medium,F,46,2484,1,0

# Label Encoding

In [4]:
df1 = df.copy()
df1

,ID,Warehouse_block,Mode_of_Shipment,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Product_importance,Gender,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N,Cluster
0,1,D,Flight,4,2,177,3,low,F,44,1233,1,0
1,2,F,Flight,4,5,216,2,low,M,59,3088,1,0
2,3,A,Flight,2,2,183,4,low,M,48,3374,1,0
3,4,B,Flight,3,3,176,4,medium,M,10,1177,1,0
4,5,C,Flight,2,2,184,3,medium,F,46,2484,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10994,10995,A,Ship,4,1,252,5,medium,F,1,1538,1,2
10995,10996,B,Ship,4,1,232,5,medium,F,6,1247,0,2
10996,10997,C,Ship,5,4,242,5,low,F,4,1155,0,2
10997,10998,F,Ship,5,2,223,6,medium,M,2,1210,0,2
10998,10999,D,Ship,2,5,155,5,low,F,6,1639,0,1

In [5]:
df1 = pd.get_dummies(df1,columns=['Mode_of_Shipment','Product_importance','Gender'], drop_first=True)
df1

,ID,Warehouse_block,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N,Cluster,Mode_of_Shipment_Road,Mode_of_Shipment_Ship,Product_importance_low,Product_importance_medium,Gender_M
0,1,D,4,2,177,3,44,1233,1,0,False,False,True,False,False
1,2,F,4,5,216,2,59,3088,1,0,False,False,True,False,True
2,3,A,2,2,183,4,48,3374,1,0,False,False,True,False,True
3,4,B,3,3,176,4,10,1177,1,0,False,False,False,True,True
4,5,C,2,2,184,3,46,2484,1,0,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10994,10995,A,4,1,252,5,1,1538,1,2,False,True,False,True,False
10995,10996,B,4,1,232,5,6,1247,0,2,False,True,False,True,False
10996,10997,C,5,4,242,5,4,1155,0,2,False,True,True,False,False
10997,10998,F,5,2,223,6,2,1210,0,2,False,True,False,True,True
10998,10999,D,2,5,155,5,6,1639,0,1,False,True,True,False,False

In [6]:
lE = LabelEncoder()
df1['Warehouse_block']=lE.fit_transform(df1['Warehouse_block'])
df1

,ID,Warehouse_block,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Discount_offered,Weight_in_gms,Reached.on.Time_Y.N,Cluster,Mode_of_Shipment_Road,Mode_of_Shipment_Ship,Product_importance_low,Product_importance_medium,Gender_M
0,1,3,4,2,177,3,44,1233,1,0,False,False,True,False,False
1,2,4,4,5,216,2,59,3088,1,0,False,False,True,False,True
2,3,0,2,2,183,4,48,3374,1,0,False,False,True,False,True
3,4,1,3,3,176,4,10,1177,1,0,False,False,False,True,True
4,5,2,2,2,184,3,46,2484,1,0,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10994,10995,0,4,1,252,5,1,1538,1,2,False,True,False,True,False
10995,10996,1,4,1,232,5,6,1247,0,2,False,True,False,True,False
10996,10997,2,5,4,242,5,4,1155,0,2,False,True,True,False,False
10997,10998,4,5,2,223,6,2,1210,0,2,False,True,False,True,True
10998,10999,3,2,5,155,5,6,1639,0,1,False,True,True,False,False

In [7]:
x = df1.drop(['Reached.on.Time_Y.N','ID'], axis=1)
x

,Warehouse_block,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Discount_offered,Weight_in_gms,Cluster,Mode_of_Shipment_Road,Mode_of_Shipment_Ship,Product_importance_low,Product_importance_medium,Gender_M
0,3,4,2,177,3,44,1233,0,False,False,True,False,False
1,4,4,5,216,2,59,3088,0,False,False,True,False,True
2,0,2,2,183,4,48,3374,0,False,False,True,False,True
3,1,3,3,176,4,10,1177,0,False,False,False,True,True
4,2,2,2,184,3,46,2484,0,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10994,0,4,1,252,5,1,1538,2,False,True,False,True,False
10995,1,4,1,232,5,6,1247,2,False,True,False,True,False
10996,2,5,4,242,5,4,1155,2,False,True,True,False,False
10997,4,5,2,223,6,2,1210,2,False,True,False,True,True
10998,3,2,5,155,5,6,1639,1,False,True,True,False,False

In [8]:
y = df1['Reached.on.Time_Y.N']
y

0        1
1        1
2        1
3        1
4        1
        ..
10994    1
10995    0
10996    0
10997    0
10998    0
Name: Reached.on.Time_Y.N, Length: 10999, dtype: int64

# Splitting Data

In [9]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

# Scaling Data

In [10]:
scaler=StandardScaler()
x_train_scaled =scaler.fit_transform(x_train)
x_train=pd.DataFrame(x_train_scaled,columns=x.columns)
x_train

,Warehouse_block,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Discount_offered,Weight_in_gms,Cluster,Mode_of_Shipment_Road,Mode_of_Shipment_Ship,Product_importance_low,Product_importance_medium,Gender_M
0,-0.894636,2.546375,0.709617,1.476283,0.268305,-0.453434,-1.113175,1.433839,-0.435204,0.689543,1.035841,-0.870496,0.99961
1,1.117773,-0.058764,-1.416196,-1.564598,-1.039087,3.128587,-1.314043,-1.543271,-0.435204,-1.450236,-0.965399,1.148771,-1.00039
2,-0.223833,-0.058764,-1.416196,0.069617,-1.039087,-0.206398,0.502928,-0.054716,-0.435204,0.689543,1.035841,-0.870496,-1.00039
3,1.117773,-0.927144,-1.416196,-0.819893,-1.039087,-0.762229,-1.217578,-0.054716,-0.435204,0.689543,1.035841,-0.870496,0.99961
4,-0.894636,0.809616,1.418221,0.772950,-1.039087,-0.576952,1.198945,-0.054716,-0.435204,0.689543,1.035841,-0.870496,0.99961
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7694,-0.223833,-0.927144,1.418221,1.331480,-1.039087,-0.391675,0.607941,-0.054716,2.297775,-1.450236,1.035841,-0.870496,-1.00039
7695,1.117773,0.809616,1.418221,-0.488912,0.268305,-0.268157,1.039594,-0.054716,2.297775,-1.450236,-0.965399,1.148771,-1.00039
7696,-1.565439,-0.058764,-0.707592,-1.523226,-1.039087,-0.700470,1.331433,-0.054716,-0.435204,0.689543,-0.965399,1.148771,-1.00039
7697,-1.565439,0.809616,0.001012,-1.378422,1.575697,1.337577,-1.596113,-1.543271,-0.435204,0.689543,-0.965399,1.148771,-1.00039
7698,-0.223833,-0.058764,0.001012,-1.150873,-0.385391,-0.700470,0.556045,-0.054716,-0.435204,-1.450236,-0.965399,-0.870496,-1.00039

In [11]:
x_test_scaled = scaler.transform(x_test)
x_test=pd.DataFrame(x_test_scaled,columns=x.columns)
x_test

,Warehouse_block,Customer_care_calls,Customer_rating,Cost_of_the_Product,Prior_purchases,Discount_offered,Weight_in_gms,Cluster,Mode_of_Shipment_Road,Mode_of_Shipment_Ship,Product_importance_low,Product_importance_medium,Gender_M
0,1.117773,-0.058764,1.418221,0.110990,-0.385391,0.781746,-0.958708,-1.543271,-0.435204,0.689543,-0.965399,-0.870496,0.99961
1,-1.565439,-0.927144,-1.416196,0.193735,-0.385391,-0.453434,1.189787,-0.054716,2.297775,-1.450236,1.035841,-0.870496,-1.00039
2,1.117773,-0.927144,-0.707592,0.090303,0.268305,-0.638711,0.255659,-0.054716,-0.435204,-1.450236,1.035841,-0.870496,-1.00039
3,0.446970,0.809616,-1.416196,-1.047442,0.922001,-0.762229,0.640300,-0.054716,-0.435204,-1.450236,1.035841,-0.870496,-1.00039
4,-0.894636,0.809616,0.709617,0.379911,-1.039087,1.893407,-0.735250,-1.543271,-0.435204,0.689543,-0.965399,1.148771,-1.00039
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3295,-1.565439,-0.927144,-1.416196,-0.675089,0.268305,-0.268157,1.284421,-0.054716,-0.435204,0.689543,-0.965399,1.148771,0.99961
3296,1.117773,-0.927144,1.418221,1.228048,-0.385391,-0.391675,0.510254,-0.054716,-0.435204,0.689543,-0.965399,-0.870496,-1.00039
3297,-0.223833,-0.927144,0.001012,1.103931,-1.039087,-0.453434,0.292291,-0.054716,-0.435204,0.689543,1.035841,-0.870496,0.99961
3298,-0.223833,-0.058764,-0.707592,1.290107,0.268305,0.781746,-0.244375,1.433839,-0.435204,0.689543,1.035841,-0.870496,-1.00039
3299,1.117773,0.809616,1.418221,-1.130187,-1.039087,-0.329916,0.728828,-0.054716,-0.435204,-1.450236,1.035841,-0.870496,-1.00039

# Modeling

In [12]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression()
LR.fit(x_train, y_train)

LogisticRegression()

In [13]:
y_pred = LR.predict(x_train)
y_pred

array([1, 1, 1, ..., 0, 1, 0], dtype=int64)

In [14]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_train, y_pred)
print(accuracy)

0.649954539550591

In [15]:
y_pred = LR.predict(x_test)
y_pred

array([1, 0, 0, ..., 1, 1, 1], dtype=int64)

In [16]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test, y_pred)
print(accuracy)

0.6478787878787878

In [17]:
from sklearn.metrics import classification_report
report = classification_report(y_test, y_pred)
print("Classification Report:")
print(report)

Classification Report:
              precision    recall  f1-score   support

           0       0.55      0.61      0.58      1312
           1       0.72      0.67      0.70      1988

    accuracy                           0.65      3300
   macro avg       0.64      0.64      0.64      3300
weighted avg       0.66      0.65      0.65      3300

54% predictions for class 0 were correct.
61 % of actual class 0 instances were correctly identified.
The accuracy of model is 65%

# Logistic Regression model with LASSO

In [18]:
lasso = LogisticRegression(penalty='l1', C=1.0, solver='liblinear')

In [19]:
lasso.fit(x_train, y_train)

LogisticRegression(penalty='l1', solver='liblinear')

In [20]:
y_pred = lasso.predict(x_test)

In [21]:
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.6454545454545455

# Random Forest Classifier

In [22]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier (n_estimators = 100,random_state = 42)

In [23]:
rf.fit(x_train, y_train)

In [ ]:
y_pred = rf.predict(x_train)
y_pred

In [ ]:
accuracy=accuracy_score(y_pred,y_train)
print(f"Accuracy: {accuracy}")

In [ ]:
pred_rf = rf.predict(x_test)

In [ ]:
accuracy = accuracy_score(pred_rf,y_test)
print(f"accuracy:{accuracy}")

In [ ]:
report2 = classification_report(y_test, pred_rf)
print("Classification Report:")
print(report2)

56% of predictions for class 0 were correct.

77% of predictions for class 1 were correct.

70% of actual class 0 instances were correctly identified.

64% of actual class 1 instances were correctly identified.

The accuracy of the model is 66%

# GradientBoostingClassifier

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
GBC = GradientBoostingClassifier(loss='log_loss',max_depth=3,
      min_samples_split=2, min_samples_leaf=1,
      learning_rate=0.1, n_estimators=100, random_state=42)

In [ ]:
GBC.fit(x_train, y_train)

In [ ]:
y_pred = GBC.predict(x_train)
y_pred

In [ ]:
accuracy = accuracy_score(y_pred,y_train)
print(f"Accuracy: {accuracy}")

In [ ]:
pred_gbc = GBC.predict(x_test)

In [ ]:
accuracy = accuracy_score(y_test,pred_gbc)

In [ ]:
report = classification_report(y_test, pred_gbc)
print(f"Accuracy: {accuracy}")
print("Classification Report:")
print(report)

# Decisiontreeclassifier

In [ ]:
from sklearn.tree import DecisionTreeClassifier
DT = DecisionTreeClassifier(criterion='gini',max_depth=5,random_state=42)

In [ ]:
DT.fit(x_train,y_train)

In [ ]:
y_pred = DT.predict(x_train)
y_pred

In [ ]:
accuracy = accuracy_score(y_pred,y_train)
print(f"Accuracy: {accuracy}")

In [ ]:
report = classification_report(y_train, y_pred)
print("Classification Report:")
print(report)

58% of predictions for class 0 were correct.

92% of predictions for class 1 were correct.

94% of actual class 0 instances were correctly identified.

53% of actual class 1 instances were correctly identified.

The accuracy of the model is 69%

In [ ]:
y_pred = DT.predict(x_test)

In [ ]:
accuracy = accuracy_score(y_pred,y_test)
print(f"Accuracy: {accuracy}")

In [ ]:
report = classification_report(y_test, y_pred)
print("Classification Report:")
print(report)

56% of predictions for class 0 were correct.

91% of predictions for class 1 were correct.

92% of actual class 0 instances were correctly identified.

53% of actual class 1 instances were correctly identified.

The accuracy of the model is 68%

# Using Decisiontree classifier give better accuracy rather than other algorithm model

# Tuning the hyperparameters

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': [None, 'sqrt', 'log2']
}

In [ ]:
grid_search = GridSearchCV(DT, param_grid, cv=5)

In [ ]:
grid_search.fit(x_train, y_train)

In [ ]:
best_params = grid_search.best_params_
best_dt_classifier = grid_search.best_estimator_

In [ ]:
best_params

In [ ]:
best_dt_classifier

In [ ]:
DT =DecisionTreeClassifier(criterion='entropy',
                           max_depth=10,
                           random_state=42,
                           min_samples_leaf= 1,
                           min_samples_split= 2)
DT.fit(x_train,y_train)

In [ ]:
y_pred_dtc1=DT.predict(x_test)
y_pred_dtc1

In [ ]:
y_pred_dtc2=DT.predict(x_train)
y_pred_dtc2

In [ ]:
accuracy=accuracy_score(y_pred_dtc2,y_train)
print(f"Accuracy: {accuracy}")

In [ ]:
accuracy=accuracy_score(y_pred_dtc1,y_test)
print(f"Accuracy: {accuracy}")

In [ ]:
report = classification_report(y_test, y_pred_dtc1)
print("Classification Report:")
print(report)

tuning the parameter reduces the accuracy of the model. Therefore using Decisiontree classifier would give better result.

# Conclusion

The importance of the products in a shipment can influence shipping decisions and potential discounts on shipping costs. 
Businesses must strike a balance between meeting customer expectations, maintaining profitability, and managing shipping 
expenses when determining discounts in the context of product shipments.

Shipping by sea is an efficient method for transporting large quantities of goods over long distances. It is commonly 
used in international trade, facilitating the movement of goods between continents and the transport of bulk cargo. 
Given the volume and distance involved, most products are shipped by sea. Efficient product shipment is crucial for 
maintaining customer satisfaction, as delays or mishandling can lead to unhappy customers.

The mode of transportation plays a significant role in delivery times. For long distances, air freight is faster than 
shipping by sea. However, factors such as weather, transportation issues, or customs delays can impact road transportation 
for short-distance deliveries. Therefore, flexibility is essential when setting delivery expectations.